/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hulkstore;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Angel Rodriguez
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    //Crea la Nocexion a BD
    Conexion  conex = new Conexion();
    Connection cone2;
    boolean Validar=false;
   
    
    public Productos() {
        initComponents();
        //Ventana fija y se quita opcion de mover o maximixar 
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        
    }
    //  lmpiar el formulario luego d euna acción
    void limpiar(){
    ID.setText("");
    Name.setText("");
    Desc.setText("");
    Stock.setText("");
    }
    //Agrerar producto 
    void Agregar( ){
     if(ID.getText().isEmpty()||Name.getText().isEmpty()||Desc.getText().isEmpty()||Stock.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Obligatorio llenar todos los campos","Campos Vacios",JOptionPane.WARNING_MESSAGE);
         }
     else {
        cone2=conex.CargarBD();
         if (cone2!=null){
                           
              try {
                  
                 Statement orden =cone2.createStatement();
                 String Consultar = "Select * from  Productos where PRODUCTOID="+ID.getText()+"";
                 ResultSet r=orden.executeQuery(Consultar);
                  while(r.next()){
                      
                        Validar=true;
                            }
                                if( Validar==false){

                                        try {
                                           Statement orden1 =cone2.createStatement();
                                           String crear = "Insert into Productos(PRODUCTOID,NOMBREPRODUCTO,DESCRIPCION,STOCK) values ("+ID.getText()+",'"+Name.getText()+"','"+Desc.getText()+"',"+Stock.getText()+")";
                                           orden1.executeUpdate(crear);
                                           JOptionPane.showMessageDialog(null, "Producto agregado Exitosamente");
                                           
                                           
                                       } catch (Exception ex) {
                                            System.out.println("Error:"+ex);
                                       }
                                }      
                                else {
                                JOptionPane.showMessageDialog(null, "Este Producto Ya existe");
                                limpiar();
                                }
             } catch (Exception ex) {
                  System.out.println("Error:"+ex);
                }
             
            
             
         }
      }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txtprod = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JLabel();
        TxtDesc = new javax.swing.JLabel();
        TxtStock = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Desc = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(530, 330));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(530, 330));
        setSize(new java.awt.Dimension(530, 330));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtprod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Txtprod.setText("Cod_Producto:");
        getContentPane().add(Txtprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        TxtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtNombre.setText("Nombre:");
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        TxtDesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtDesc.setText("Descripción:");
        getContentPane().add(TxtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        TxtStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TxtStock.setText("Stock:");
        getContentPane().add(TxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 110, -1));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 380, -1));
        getContentPane().add(Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 380, -1));

        Stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StockKeyTyped(evt);
            }
        });
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, -1));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Añadir Nuevos Productos ");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 30));

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Add New_16px.png"))); // NOI18N
        Agregar.setText("Agregar Producto");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Back.png"))); // NOI18N
        Regresar.setText("Regresar ");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 130, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/NBG.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        
    }//GEN-LAST:event_IDActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        Agregar();
        limpiar();
    }//GEN-LAST:event_AgregarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        //volver al Menú Principal 
        HulkStore volver=new HulkStore();
        volver.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void StockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockKeyTyped
        // Condiciona para que la cantidad sea solonumerica
         char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_StockKeyTyped
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          
        try {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (InstantiationException ex) {
                Logger.getLogger(HulkStore.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(HulkStore.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(HulkStore.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            System.err.println("Error:"+ex);    
        } 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel BG;
    private javax.swing.JTextField Desc;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField Stock;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TxtDesc;
    private javax.swing.JLabel TxtNombre;
    private javax.swing.JLabel TxtStock;
    private javax.swing.JLabel Txtprod;
    // End of variables declaration//GEN-END:variables
}
